// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsxmh5p_WbY0YgXdyGS5wyT-rE135jJ9U',
    appId: '1:566656155093:web:316d3e7624dfd1dd2b515c',
    messagingSenderId: '566656155093',
    projectId: 'the-bloom-room-6f3ad',
    authDomain: 'the-bloom-room-6f3ad.firebaseapp.com',
    storageBucket: 'the-bloom-room-6f3ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxTMuCSGB-VELtH-MAro1cHH_Aw91Qd8A',
    appId: '1:566656155093:android:8161bef0fbfe599b2b515c',
    messagingSenderId: '566656155093',
    projectId: 'the-bloom-room-6f3ad',
    storageBucket: 'the-bloom-room-6f3ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbNS9mzlXPazTJ-CuYPsKxp9EHzAx6kWc',
    appId: '1:566656155093:ios:9d90e640ba6176442b515c',
    messagingSenderId: '566656155093',
    projectId: 'the-bloom-room-6f3ad',
    storageBucket: 'the-bloom-room-6f3ad.appspot.com',
    iosBundleId: 'com.example.theBloomRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbNS9mzlXPazTJ-CuYPsKxp9EHzAx6kWc',
    appId: '1:566656155093:ios:74e536b4431efba32b515c',
    messagingSenderId: '566656155093',
    projectId: 'the-bloom-room-6f3ad',
    storageBucket: 'the-bloom-room-6f3ad.appspot.com',
    iosBundleId: 'com.example.theBloomRoom.RunnerTests',
  );
}
